### ISSUE TITLE
Support for Validation Module

### ISSUE THREAD

**Issue by rumbafum** [Terricks/XAFBootstrap#28]
I'm trying to make it wok with version 16.1 for now. This error occurs when using Validation Module. Can you give some insight on what could be the issue.

The error occurred:

	Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at DevExpress.ExpressApp.Web.Utils.ClientSideEventsHelper.AssignClientHandlerSafe(ASPxWebControl editor, String eventName, String script, String key)
   at DevExpress.ExpressApp.Validation.Web.InplaceValidationHelperWeb.ApplyEditorValidationSettings(ASPxEdit editor, IList`1 ruleList, Object currentObject, Type memberType, String validationOnInitScript, RequiredFieldValidationType requiredFieldValidationType)
   at DevExpress.ExpressApp.Validation.Web.InplaceEditorsValidationControllerWeb.ApplyPropertyEditorValidationSettings(PropertyEditor propertyEditor, IList`1 ruleList)
   at DevExpress.ExpressApp.Validation.InplaceEditorsValidationControllerBase.PropertyEditor_ControlCreated(Object sender, EventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at DevExpress.ExpressApp.Editors.ViewItem.OnControlCreated()
   at XafBootstrap.Web.HTMLViewItem.OnInit(EventArgs e) in C:\Users\eduardo\Documents\Visual Studio 2015\Projects\Solution1\XAF Bootstrap\Templates\XafBootstrapView.ascx.cs:line 126
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at XafBootstrap.Web.XafBootstrapView.AddContent(Control control, Object DataContainer) in C:\Users\eduardo\Documents\Visual Studio 2015\Projects\Solution1\XAF Bootstrap\Templates\XafBootstrapView.ascx.cs:line 242
   at XafBootstrap.Web.XafBootstrapView.BuildRecursiveElement(Control control, Control Parent, ElemType type, Object Container) in C:\Users\eduardo\Documents\Visual Studio 2015\Projects\Solution1\XAF Bootstrap\Templates\XafBootstrapView.ascx.cs:line 853
   at XafBootstrap.Web.XafBootstrapView.BuildContent() in C:\Users\eduardo\Documents\Visual Studio 2015\Projects\Solution1\XAF Bootstrap\Templates\XafBootstrapView.ascx.cs:line 876
   at XafBootstrap.Web.XafBootstrapView.InnerRender() in C:\Users\eduardo\Documents\Visual Studio 2015\Projects\Solution1\XAF Bootstrap\Templates\XafBootstrapView.ascx.cs:line 216
   at XafBootstrap.Web.XafBootstrapView.OnInit(EventArgs e) in C:\Users\eduardo\Documents\Visual Studio 2015\Projects\Solution1\XAF Bootstrap\Templates\XafBootstrapView.ascx.cs:line 904

**Comment by Terricks** [comment]
Hi, there are a couple of controllers that conflicts with XAFBootstrap - so we have deactivated them (like Focus Controller) - and made own.
It seems that here is same situation. Try to disable InplaceEditorsValidationControllerWeb.

**Comment by rumbafum** [comment]
Thanks! I'll try that
