### ISSUE TITLE
Assigning 'null' to webwindow 

### ISSUE THREAD

**Issue by rajkamal0610** [Terricks/XAFBootstrap#29]
HI,

Recently I reviewed a document regarding Boost strap for XAF new style. It's good to see and use. Thanks for providing such option.

But while implementing in devexpress 16.2.3 based xaf solution it gets error immediately when pressed logon. I know that u have applied this option and verified in Devexpress v15.2. Me too using the same. But somehow I need to provide the same option in v16.2

kindly provide me an idea / guide me to get out of the issue.

Thanks In Advance
Warn Regards.

**Comment by Terricks** [comment]
Hi, thank you for using XAF Bootstrap.
We haven't tested it with 16.2 yet, but we plan to prepare solution after New Year (maybe in January).
If you provide a trace log of error - we could say more about it.

**Comment by rajkamal0610** [comment]
Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at DevExpress.ExpressApp.Web.SystemModule.FocusController.ClearHolders()
   at DevExpress.ExpressApp.Web.SystemModule.FocusController.OnDeactivated()
   at DevExpress.ExpressApp.Controller.activeList_ResultValueChanged(Object sender, BoolValueChangedEventArgs e)
   at DevExpress.ExpressApp.Utils.BoolList.OnResultValueChanged(Boolean oldResultValue, Boolean resultValue)
   at DevExpress.ExpressApp.Utils.BoolList.EndUpdate()
   at DevExpress.ExpressApp.Utils.BoolList.set_Item(String key, Boolean value)
   at DevExpress.ExpressApp.Frame.<>c__DisplayClass4.<Dispose>b__1()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
   at DevExpress.ExpressApp.Frame.Dispose()
   at DevExpress.Persistent.Base.SafeExecutor.<>c__DisplayClass1.<Dispose>b__0()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
   at DevExpress.Persistent.Base.SafeExecutor.Dispose(IDisposable targetObject, String targetObjectIdentifier)
   at DevExpress.Persistent.Base.SafeExecutor.Dispose(IDisposable targetObject)
   at DevExpress.ExpressApp.Web.WebApplication.DisposeCore()
   at DevExpress.ExpressApp.XafApplication.<Dispose>b__1()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
   at DevExpress.ExpressApp.XafApplication.Dispose(Boolean disposing)
   at DevExpress.ExpressApp.XafApplication.Dispose()
   at DevExpress.ExpressApp.Web.WebApplication.DisposeInstance(HttpSessionState session)
	InnerException is null


Type: Exception
Message: An error with number 1079 has occurred.
Error message: Unknown exception occurs. Cannot retrieve the exception details
Data: 0 entries
Stack trace:
InnerException is null

**Comment by rajkamal0610** [comment]
Type:       Exception
	Message:    An error with number 1079 has occurred.
Error message: Unknown exception occurs. Cannot retrieve the exception details
	Data:       0 entries
	Stack trace:


	InnerException is null

**Comment by Terricks** [comment]
Thank you,
It needs more time to research this.
For now you can disable XAF Bootstrap custom login page - to do this you have to comment code listed below:
https://github.com/Terricks/XAFBootstrap/blob/master/XAF%20Bootstrap/Module.cs#L97#L99

**Comment by rajkamal0610** [comment]
Have the same project committed for devexpress xaf v16.2
